### ISSUE TITLE
TRS-80 pointer to Kyotronic

### ISSUE THREAD

**Issue by hackerb9** [robhagemans/hoard-of-bitfonts#7]
Since few people know the name "Kyocera Kyotronic-85", but the "TRS-80 Model 100" is well known, it would be good if trs-80/README.md had a pointer to the kyotronic.yaff file. It could say something like, 

> Note that font used in the TRS-80 Model 100 is the same as the [kyotronic-85 font](../kyotronic-85.yaff). Likewise, see the [kyotronic](../kyotronic) directory for the [font used in the Tandy 200 and Tandy 102](../kyotronic/tandy-200.yaff) and the TRS-80 Disk/Video Interface [40-column](../kyotronic/trs80-dvi-7x8.yaff) and [80-column font](../kyotronic/trs80-dvi-8x8.yaff).

Additionally, it would be a nice touch if the files would _appear_ to also be in the trs-80 directory. GitHub handles symlinks, so it should be as simple as:

```bash
cd trs-80
ln  -s  ../kyotronic/kyotronic-85.yaff  trs80-model100.yaff
ln  -s  ../kyotronic/tandy-200.yaff 
ln  -s  ../kyotronic/trs80-dvi-7x8.yaff 
ln  -s  ../kyotronic/trs80-dvi-8x8.yaff 
ln  -s  tandy-200.yaff  tandy-102.yaff
git add *
git commit -m "TRS-80 portables are variants of the Kyocera Kyotronic-85"
```

**Comment by hackerb9** [comment]
By the way: Symlinks may not be well supported by git on Microsoft Windows — I think one has to check a box during installation — but it's still better to have these links than not. I'm guessing that most people will be browsing the project using GitHub's web interface, not through git, so symlinks will work seamlessly. Being UNIX, GNU/Linux and Apple MacOS work fine. The only case where it would not work is if someone used 'git clone' from a Microsoft Windows machine which did not have symlinks enabled. The failure state is minor: a symlink would seem to contain the text of the correct path to open.

**Comment by robhagemans** [comment]
Hi,

Sorry, I'm not going to put in symlinks, it'll just become harder to
manage. I may put in some reference in the README at some point but I don't
think it's super important, and the more references I make the harder it
will be to reorganise later. There are many, many other machines that are
stored in odd locations in that repo, mostly because they are in some way
related to another line of machines. A search for TRS-80 in the repo will
already bring up the kyotronic directory, with a README indicating which
font is for the Model 100, so it's not terribly difficult to find.
